services:
  db_copilot_backend:
    platform: linux/arm64
    build:
      context: ./backend
    user: "horse"
    volumes:
      - /home/horse/www/db-arch-copilot/backend/storage:/rails/storage
        # healthcheck:
        #   test: curl --fail http://localhost:3000/up || exit 1
        #   interval: 30s
        #   timeout: 30s
        #   retries: 5
        #   start_period: 30s
  db_copilot_frontend:
    platform: linux/arm64
    build:
      context: ./frontend
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://0.0.0.0:3000 || exit 1
    #   interval: 30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
