services:
  backend:
    platform: linux/arm64
    build:
      context: ./backend
    ports:
      - "3001:3000"

    volumes:
      - /home/horse/www/ai-db-architecture-consultant-project/backend:/rails
